spring.application.name=gestao-condominio-api

# Configuração do Servidor
server.port=8080

# Configuração do Banco de Dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/condominio_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=andrerosa98
spring.datasource.password=159875
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuração do JPA (Hibernate é a implementação padrão)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
